### ISSUE TITLE
Linux 5.1.7 hash?

### ISSUE THREAD

**Issue by kdtsh** [ison5002/guix-g#3]
Hey there, thanks for managing this repository.

Call me crazy but does the hash you have for linux-5.1.7.tar.xz check out for you? 'guix system reconfigure' fails for me due to an invalid hash on linux-5.1.7.tar.xz. When I run 'guix hash linux-5.1.7.tar.xz' on a downloaded tarball, I get almost the same but without the 'i' prepended - i.e. '19pkmnvpjacrssyyjhjlz8cqi8fsn3y293yyvc5bv6dpy96x0ih2'. Did you edit with with vi and accidentally add an 'i' at the front of the hash?

**Comment by ison5002** [comment]
> Did you edit with with vi and accidentally add an 'i' at the front of the hash?
Yup, that's exactly what happened. Sorry about that. The first time I updated the repo without testing it first too.
It's fixed now. I'll have to be more careful in the future.
Thanks for catching it.
